### ISSUE TITLE
Error when running semi.tgtinfer()

### ISSUE THREAD

**Issue by Weimin-LinA** [mcgilldinglab/scSemiProfiler#2]
Hi mcgilldinglab,

When I try this function:
semi.tgtinfer(name = name, representative = 6, target = 1, bulktype='pseudobulk', device= 'cuda:0')

I got an error like this:
"--> 140 model.train(max_epochs=vaesteps, plan_kwargs={'lr':lr,'lr2':1e-10,'kappa':4},use_gpu=device)
TypeError: Trainer.__init__() got an unexpected keyword argument 'use_gpu'"
But i did not find the keyword argument in the code I input. It seems like an error in the inside function 'Trainer.__init__() ', it didnot have a argument 'use_gpu'.

Thanks!

**Comment by JingtaoWang22** [comment]
Hi Weimin,

Thank you for your feedback. I'm happy to help with the issue.

I looked into this and could not reproduce this error. I've updated the repository with the latest version of the code. Could you try it as well?

It is also possible that this issue is caused by mismatched dependency package versions (probably pytorch lightning. mine is 2.1.1).  To better identify the problem, could you send me the package versions in your conda environment by providing the output of the conda list command? If this is indeed the reason, I will improve the installation.

Please let me know if this resolves the issue.

Jingtao

**Comment by ly18803463685** [comment]
> Hi Weimin,
> 
> Thank you for your feedback. I'm happy to help with the issue.
> 
> I looked into this and could not reproduce this error. I've updated the repository with the latest version of the code. Could you try it as well?
> 
> It is also possible that this issue is caused by mismatched dependency package versions (probably pytorch lightning. mine is 2.1.1). To better identify the problem, could you send me the package versions in your conda environment by providing the output of the conda list command? If this is indeed the reason, I will improve the installation.
> 
> Please let me know if this resolves the issue.
> 
> Jingtao

Hi Jingtao,

**Comment by ly18803463685** [comment]
Hi jingtao,

I got the same error when I run "semi.tgtinfer(name = name, representative = 6, target = 1, bulktype=bulktype)“，I try to downgrade pytorch-lightning to 2.1.1, but not work. Here are my error report:

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/home/liyang/deeplearning/scSemiProfiler-main/scSemiProfiler/inference.py", line 593, in tgtinfer
    repremodel = fastrecon(name=name,sid=rp,device=device,k=15,diagw=1,vaesteps=int(pretrain1vae),gansteps=int(pretrain1gan),save=True,path=None)\
  File "/share/home/liyang/deeplearning/scSemiProfiler-main/scSemiProfiler/inference.py", line 135, in fastrecon
    model.train(max_epochs=vaesteps, plan_kwargs={'lr':lr,'lr2':0,'kappa':4.0},use_gpu=device)
  File "/share/home/liyang/deeplearning/scSemiProfiler-main/scSemiProfiler/vaegan.py", line 1372, in train
    runner = TrainRunner(
  File "/share/home/liyang/miniconda3/envs/semiprofiler/lib/python3.9/site-packages/scvi/train/_trainrunner.py", line 82, in __init__
    self.accelerator = accelerator
  File "/share/home/liyang/miniconda3/envs/semiprofiler/lib/python3.9/site-packages/scvi/train/_trainer.py", line 172, in __init__
    # https://github.com/PyTorchLightning/pytorch-lightning/blob/
  File "/share/home/liyang/miniconda3/envs/semiprofiler/lib/python3.9/site-packages/lightning/pytorch/utilities/argparse.py", line 70, in insert_env_defaults
TypeError: __init__() got an unexpected keyword argument 'use_gpu'”

**Comment by JingtaoWang22** [comment]
Installation has been updated to avoid package discrepancies.
