### ISSUE TITLE
Error caused by version of anndata

### ISSUE THREAD

**Issue by Alsafadi** [mcgilldinglab/scSemiProfiler#3]
There is an error caused by version of anndata when importing scSemiProfiler in the example in the documentation. 

`cannot import name 'AlignedViewMixin' from 'anndata._core.aligned_mapping'`

This was fixed by downgrading anndata:

`pip install anndata==0.10.8`

**Comment by JingtaoWang22** [comment]
Thank you for finding this. I have updated the installation to avoid this type of issues.
