### ISSUE TITLE
assemble_cohort error

### ISSUE THREAD

**Issue by linzhengmix** [mcgilldinglab/scSemiProfiler#4]
Dear authors,

Thanks for your amazing tools of scSemiProfiler!

Could you have a look at the error: KeyError: 'states_collection_sum' when I run the function "assemble_cohort"

The error messages are as follows
`--------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/anaconda3/envs/semiprofiler/lib/python3.9/site-packages/pandas/core/indexes/base.py:3790, in Index.get_loc(self, key)
   3789 try:
-> 3790     return self._engine.get_loc(casted_key)
   3791 except KeyError as err:

File index.pyx:152, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:181, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'states_collection_sum'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[32], line 3
      1 representatives = repres
      2 cluster_labels = cl
----> 3 semisdata = assemble_cohort(name,
      4                 representatives,
      5                 cluster_labels,
      6                 celltype_key = 'celltypes',
      7                 sample_info_keys = ['states_collection_sum'],
      8                 bulkpath = 'example_data/bulkdata.h5ad',
      9                 annotator = MLPClassifier(hidden_layer_sizes=(200,)))

File /mnt/data/zhenglin/scSemiProfiler/scSemiProfiler/scSemiProfiler/utils.py:558, in assemble_cohort(name, representatives, cluster_labels, celltype_key, sample_info_keys, bulkpath, annotator)
    556         for k in sample_info_keys:
    557             for j in range(x.shape[0]):
--> 558                 sampleinfo[k].append(bulkdata.obs[k][i])
    560 semidata = anndata.AnnData(np.array(np.concatenate(X)))
    561 semidata.obs['source'] = source

File ~/anaconda3/envs/semiprofiler/lib/python3.9/site-packages/pandas/core/frame.py:3893, in DataFrame.__getitem__(self, key)
   3891 if self.columns.nlevels > 1:
   3892     return self._getitem_multilevel(key)
-> 3893 indexer = self.columns.get_loc(key)
   3894 if is_integer(indexer):
   3895     indexer = [indexer]

File ~/anaconda3/envs/semiprofiler/lib/python3.9/site-packages/pandas/core/indexes/base.py:3797, in Index.get_loc(self, key)
   3792     if isinstance(casted_key, slice) or (
   3793         isinstance(casted_key, abc.Iterable)
   3794         and any(isinstance(x, slice) for x in casted_key)
   3795     ):
   3796         raise InvalidIndexError(key)
-> 3797     raise KeyError(key) from err
   3798 except TypeError:
   3799     # If we have a listlike key, _check_indexing_error will raise
   3800     #  InvalidIndexError. Otherwise we fall through and re-raise
   3801     #  the TypeError.
   3802     self._check_indexing_error(key)

KeyError: 'states_collection_sum'

Thanks

**Comment by JingtaoWang22** [comment]
Hello, I'm happy to help.

Are you using your own dataset or the example dataset? 'states_collection_sum' is in my example dataset recording the disease severity information. Including this key here is for automatically label the new generated data with this information. If you are using your own datset, you can replace it with an empty list [] or any other key that you want to transfer from your original dataset to your new dataset.

Feel free to follow up or email us if you have further questions

**Comment by JingtaoWang22** [comment]
updated data and utils to avoid this bug.

**Comment by linzhengmix** [comment]
Great job, thanks!
